apiVersion: apps/v1
kind: Deployment
metadata:
  name: volumes-nfs
spec:
  selector:
    matchLabels:
      homework: task2nfs
  template:
    metadata:
      labels:
        homework: task2nfs
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: nfs-storage
          mountPath: /shared_folder3
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc