apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-multitool
spec:
  ports:
    - name: nginx-port
      port: 9001
      targetPort: 80
    - name: multitool-port
      port: 9002
      targetPort: 8080
  selector:
    app: my-web
