apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-multitool-2
spec:
  ports:
    - name: http-nginx
      port: 80
      nodePort: 32000
    - name: http-multitool
      port: 8080
      nodePort: 32001
  selector:
    app: my-web
  type: NodePort